import { StateGraph, START, MessagesAnnotation } from "@langchain/langgraph";
import { ToolNode, toolsCondition } from "@langchain/langgraph/prebuilt";
import { ChatGroq } from "@langchain/groq";
import { BaseMessage, SystemMessage } from "@langchain/core/messages";
import { allTools } from "./tools";

// ========================================
// 1. LLM & EMBEDDINGS CONFIG
// ========================================

const modelName = process.env.GROQ_MODEL || "qwen/qwen3.8-27b";
export const embeddingModelName = process.env.EMBEDDING_MODEL || "gemini-embedding-001";

const llm = new ChatGroq({
  model: modelName,
  apiKey: process.env.GROQ_API_KEY,
  temperature: 0,
});

const llmWithTools = llm.bindTools(allTools);

// ========================================
// 2. CHATBOT NODE & GRAPH SETUP
// ========================================

async function chatbotNode(state: typeof MessagesAnnotation.State) {
  const response = await llmWithTools.invoke(state.messages);
  return {
    messages: [response],
  };
}

const toolNode = new ToolNode(allTools);

const graph = new StateGraph(MessagesAnnotation)
  .addNode("chatbot", chatbotNode)
  .addNode("tools", toolNode)
  .addEdge(START, "chatbot")
  .addConditionalEdges("chatbot", toolsCondition)
  .addEdge("tools", "chatbot")
  .compile();

// ========================================
// 3. MAIN AGENT RUNNER EXPORT
// ========================================

export interface RunAgentInput {
  messages: BaseMessage[];
  userId: number;
  conversationId: number;
  fileUrl?: string | null;
  fileType?: string | null;
}

export interface AgentResponse {
  content: string;
  type: string;
  file_url: string | null;
}

export async function runAgent({
  messages,
  userId,
  conversationId,
  fileUrl,
  fileType,
}: RunAgentInput): Promise<AgentResponse> {
  const inputMessages = [...messages];

  let systemText = `You are a helpful AI assistant.
Available tools to call:
- generateImage: Call this tool whenever the user asks to generate, create, make, or draw an image.
- analyzeImage: Call this tool when asked about an attached image.
- getWeather: Call this tool for live weather.
- calculator: Call this tool for math calculations.

NOTE: 'JSON' IS NOT A TOOL. Do NOT attempt to invoke any tool named 'JSON' or 'json'.
We only use JSON formatting to store responses in our database.

CRITICAL INSTRUCTIONS FOR IMAGE GENERATION & MEDIA HANDLING:
1. If generating an image, PDF, or anything, and the generateImage tool returns an image URL, you MUST place that exact URL in "file_url" and set "type": "image" in your final JSON response so it is stored for future use.
2. Do NOT format the image URL as markdown links inside "content".
3. Note: The URL of a PDF will not be of much use directly as embeddings are generated for PDF contents; search in the database for that information.

For your final answer, please format your text response as a raw JSON string matching this schema:
{
  "content": "Your text response or explanation here",
  "type": "text" | "image" | "pdf",
  "file_url": "Exact URL if generated by generateImage tool or attached file, otherwise null"
}`;

  if (fileUrl) {
    systemText += `\nUser attached a ${fileType || "file"}. Attached File URL: ${fileUrl}. If user asks questions about the image, call analyzeImage tool with imageUrl: "${fileUrl}".`;
  }

  inputMessages.unshift(new SystemMessage(systemText));

  const result = await graph.invoke({ messages: inputMessages });
  const finalMessage = result.messages.at(-1);
  const text = String(finalMessage?.content || "");

  try {
    const parsed = JSON.parse(text);
    return {
      content: parsed.content || text,
      type: parsed.type || "text",
      file_url: parsed.file_url || null,
    };
  } catch {
    return {
      content: text,
      type: "text",
      file_url: null,
    };
  }
}
