import { tool } from "@langchain/core/tools";
import { z } from "zod";
import PDFDocument from "pdfkit";
import { uploadBufferToCloudinary } from "../../lib/clodinary";

export const generatePdfTool = tool(
  async ({ title, content }) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => buffers.push(chunk));

      // Document Header
      doc
        .fontSize(22)
        .font("Helvetica-Bold")
        .fillColor("#1e293b")
        .text(title, { align: "center" });

      doc.moveDown(1.5);

      // Document Body
      doc
        .fontSize(12)
        .font("Helvetica")
        .fillColor("#334155")
        .text(content, {
          align: "justify",
          lineGap: 4,
        });

      doc.moveDown(2);

      // Document Footer
      doc
        .fontSize(9)
        .fillColor("#94a3b8")
        .text(`Generated by EMCA AI • ${new Date().toLocaleDateString()}`, {
          align: "center",
        });

      doc.end();

      const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
        doc.on("end", () => resolve(Buffer.concat(buffers)));
        doc.on("error", (err) => reject(err));
      });

      // Upload to Cloudinary using existing uploadBufferToCloudinary function
      const uploadRes = await uploadBufferToCloudinary(
        pdfBuffer,
        `pdf_${Date.now()}`,
        "raw",
      );

      return uploadRes.secure_url;
    } catch (error) {
      console.error("PDF generation tool error:", error);
      return `Error generating PDF document: ${
        error instanceof Error ? error.message : String(error)
      }`;
    }
  },
  {
    name: "generatePdf",
    description:
      "Generate a PDF document based on user request title and content, upload it, and return the secure PDF URL.",
    schema: z.object({
      title: z
        .string()
        .describe("The main title or heading of the PDF document."),
      content: z
        .string()
        .describe("The full text content or report to include inside the PDF."),
    }),
  },
);
